<?php
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    echo "Pedro <br>";
    echo 'Pedro <br>';
    echo "Pedro 'Fernandes'";
    // Kappa exercise.
